package confgen

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/reloadlife/openvpnd/internal/db"
	"github.com/reloadlife/openvpnd/internal/features"
	"github.com/reloadlife/openvpnd/internal/netutil"
)

// RenderOptions optionally supplies custom feature presets from the DB.
type RenderOptions struct {
	CustomPresets []db.FeaturePreset
	// BandwidthEnforcement: off|tc|shaper|log — when "shaper", emit global OpenVPN --shaper
	// from the max of client bandwidth_* limits (bytes/sec). No per-client shaping in conf.
	BandwidthEnforcement string
}

// Paths holds runtime path helpers for an instance.
type Paths struct {
	ConfDir    string
	RuntimeDir string
	Name       string
}

func (p Paths) ConfFile() string {
	return filepath.Join(p.ConfDir, p.Name+".conf")
}

func (p Paths) PIDFile() string {
	return filepath.Join(p.RuntimeDir, p.Name+".pid")
}

func (p Paths) MgmtSock() string {
	return filepath.Join(p.RuntimeDir, p.Name+".mgmt.sock")
}

func (p Paths) StatusFile() string {
	return filepath.Join(p.RuntimeDir, p.Name+".status")
}

func (p Paths) CCDDir() string {
	return filepath.Join(p.ConfDir, "ccd", p.Name)
}

// TmpDir is a writable temp directory for openvpn under RuntimeDir
// (avoids systemd ProtectSystem=/tmp read-only failures).
func (p Paths) TmpDir() string {
	return filepath.Join(p.RuntimeDir, "tmp")
}

// RenderResult is generated conf content.
type RenderResult struct {
	Content string
	Hash    string
}

// Hash returns sha256 hex of content.
func Hash(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

// RenderInstance builds an OpenVPN conf for the instance.
// Management/status/pid are always injected for daemon control.
func RenderInstance(inst db.Instance, paths Paths, clients []db.Client) (RenderResult, error) {
	return RenderInstanceOpts(inst, paths, clients, RenderOptions{})
}

// RenderInstanceOpts is RenderInstance with custom feature presets.
func RenderInstanceOpts(inst db.Instance, paths Paths, clients []db.Client, opts RenderOptions) (RenderResult, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by openvpnd — do not edit by hand\n")
	fmt.Fprintf(&b, "# instance=%s role=%s\n", inst.Name, inst.Role)

	// Expand feature sets → plugins / env / extra (env applied by process supervisor).
	extra, plugins, _ := features.Expand(inst.FeatureSets, opts.CustomPresets, inst.ExtraDirectives, inst.Plugins, inst.EnvVars)

	// Plugins early so they can hook lifecycle
	for _, pl := range plugins {
		if pl.Path == "" {
			continue
		}
		fmt.Fprintf(&b, "plugin %s", pl.Path)
		for _, a := range pl.Args {
			fmt.Fprintf(&b, " %s", quoteArg(a))
		}
		fmt.Fprintf(&b, "\n")
	}

	dev := inst.DevType
	if dev == "" {
		dev = "tun"
	}
	if inst.Device != "" {
		fmt.Fprintf(&b, "dev %s\n", inst.Device)
		fmt.Fprintf(&b, "dev-type %s\n", dev)
	} else {
		fmt.Fprintf(&b, "dev %s\n", dev)
	}

	proto := inst.Proto
	if proto == "" {
		proto = "udp"
	}
	fmt.Fprintf(&b, "proto %s\n", proto)

	if inst.LocalBind != "" {
		fmt.Fprintf(&b, "local %s\n", inst.LocalBind)
	}

	switch inst.Role {
	case "server":
		if err := renderServer(&b, inst, paths); err != nil {
			return RenderResult{}, err
		}
	case "client":
		if err := renderClient(&b, inst); err != nil {
			return RenderResult{}, err
		}
	default:
		return RenderResult{}, fmt.Errorf("unknown role %q", inst.Role)
	}

	// Crypto paths.
	// StaticKeyPath is dual-purpose:
	//   - AuthMode=static_key → OpenVPN "secret" (point-to-point static key)
	//   - otherwise (PKI)     → "tls-auth" HMAC key (common on commercial client .ovpn)
	if inst.AuthMode == "static_key" {
		if inst.StaticKeyPath != "" {
			fmt.Fprintf(&b, "secret %s\n", inst.StaticKeyPath)
		}
	} else {
		if inst.PKICaPath != "" {
			fmt.Fprintf(&b, "ca %s\n", inst.PKICaPath)
		}
		if inst.PKICertPath != "" {
			fmt.Fprintf(&b, "cert %s\n", inst.PKICertPath)
		}
		if inst.PKIKeyPath != "" {
			fmt.Fprintf(&b, "key %s\n", inst.PKIKeyPath)
		}
		if inst.Role == "server" {
			if inst.PKIDHPath != "" {
				fmt.Fprintf(&b, "dh %s\n", inst.PKIDHPath)
			} else {
				fmt.Fprintf(&b, "dh none\n")
			}
		}
		if inst.PKITLSCryptPath != "" {
			fmt.Fprintf(&b, "tls-crypt %s\n", inst.PKITLSCryptPath)
		}
		if inst.StaticKeyPath != "" {
			// key-direction (if any) is preserved via extra_directives from import/adopt.
			fmt.Fprintf(&b, "tls-auth %s\n", inst.StaticKeyPath)
		}
		if inst.Role == "server" && inst.PKICRLPath != "" {
			fmt.Fprintf(&b, "crl-verify %s\n", inst.PKICRLPath)
		}
	}

	if inst.Cipher != "" {
		fmt.Fprintf(&b, "cipher %s\n", inst.Cipher)
	}
	if inst.DataCiphers != "" {
		fmt.Fprintf(&b, "data-ciphers %s\n", inst.DataCiphers)
	}
	if inst.AuthDigest != "" {
		fmt.Fprintf(&b, "auth %s\n", inst.AuthDigest)
	}
	if inst.TLSVersionMin != "" {
		fmt.Fprintf(&b, "tls-version-min %s\n", inst.TLSVersionMin)
	}
	if inst.TLSCipher != "" {
		fmt.Fprintf(&b, "tls-cipher %s\n", inst.TLSCipher)
	}
	if inst.TLSCiphersuites != "" {
		fmt.Fprintf(&b, "tls-ciphersuites %s\n", inst.TLSCiphersuites)
	}
	if inst.TLSGroups != "" {
		fmt.Fprintf(&b, "tls-groups %s\n", inst.TLSGroups)
	}
	if inst.TLSCertProfile != "" {
		fmt.Fprintf(&b, "tls-cert-profile %s\n", inst.TLSCertProfile)
	}
	if inst.TunMTU > 0 {
		fmt.Fprintf(&b, "tun-mtu %d\n", inst.TunMTU)
	}
	if inst.Sndbuf > 0 {
		fmt.Fprintf(&b, "sndbuf %d\n", inst.Sndbuf)
	}
	if inst.Rcvbuf > 0 {
		fmt.Fprintf(&b, "rcvbuf %d\n", inst.Rcvbuf)
	}
	if inst.IfconfigIPv6 != "" {
		fmt.Fprintf(&b, "ifconfig-ipv6 %s\n", inst.IfconfigIPv6)
	}
	if inst.Role == "client" {
		if strings.TrimSpace(inst.AuthUserPassFile) != "" {
			fmt.Fprintf(&b, "auth-user-pass %s\n", strings.TrimSpace(inst.AuthUserPassFile))
		} else if inst.AuthUserPass {
			fmt.Fprintf(&b, "auth-user-pass\n")
		}
	}
	if inst.Role == "server" && strings.TrimSpace(inst.AuthUserPassVerify) != "" {
		sec := inst.ScriptSecurity
		if sec == 0 {
			sec = 2
		}
		fmt.Fprintf(&b, "script-security %d\n", sec)
		method := "via-file"
		if sec >= 2 {
			method = "via-env"
		}
		fmt.Fprintf(&b, "auth-user-pass-verify %s %s\n", strings.TrimSpace(inst.AuthUserPassVerify), method)
		if inst.UsernameAsCommonName {
			fmt.Fprintf(&b, "username-as-common-name\n")
		}
	}

	fmt.Fprintf(&b, "keepalive 10 60\n")
	fmt.Fprintf(&b, "persist-key\n")
	fmt.Fprintf(&b, "persist-tun\n")

	// tmp-dir must be writable under ProtectSystem=strict (systemd remounts /tmp RO).
	fmt.Fprintf(&b, "tmp-dir %s\n", paths.TmpDir())
	fmt.Fprintf(&b, "writepid %s\n", paths.PIDFile())
	fmt.Fprintf(&b, "status %s 1\n", paths.StatusFile())
	fmt.Fprintf(&b, "management %s unix\n", paths.MgmtSock())
	fmt.Fprintf(&b, "management-client-user root\n")
	fmt.Fprintf(&b, "verb 3\n")

	if extra != "" {
		fmt.Fprintf(&b, "\n# extensions (feature_sets + extra_directives)\n%s\n", extra)
	}

	// Global OpenVPN --shaper (outgoing only). Per-client shaping is tc/log via reconciler.
	if strings.EqualFold(strings.TrimSpace(opts.BandwidthEnforcement), "shaper") && inst.Role == "server" {
		var maxBits int64
		for _, c := range clients {
			if c.BandwidthRxBps > maxBits {
				maxBits = c.BandwidthRxBps
			}
			if c.BandwidthTxBps > maxBits {
				maxBits = c.BandwidthTxBps
			}
		}
		if maxBits > 0 {
			// --shaper takes bytes/sec; client fields are bits/sec (see bandwidth package).
			bytesPerSec := maxBits / 8
			if bytesPerSec < 1 {
				bytesPerSec = 1
			}
			fmt.Fprintf(&b, "\n# bandwidth_enforcement=shaper (global outgoing; max of client limits)\n")
			fmt.Fprintf(&b, "shaper %d\n", bytesPerSec)
		} else if len(clients) > 0 {
			fmt.Fprintf(&b, "\n# bandwidth_enforcement=shaper: no client bandwidth_* limits set\n")
		}
	}

	content := b.String()
	return RenderResult{Content: content, Hash: Hash(content)}, nil
}

func quoteArg(a string) string {
	if a == "" {
		return `""`
	}
	if strings.ContainsAny(a, " \t\"'") {
		return `"` + strings.ReplaceAll(a, `"`, `\"`) + `"`
	}
	return a
}

func renderServer(b *strings.Builder, inst db.Instance, paths Paths) error {
	port := inst.Port
	if port == 0 {
		port = 1194
	}
	fmt.Fprintf(b, "port %d\n", port)
	fmt.Fprintf(b, "mode server\n")
	fmt.Fprintf(b, "tls-server\n")

	if inst.BridgeMode {
		gw := strings.TrimSpace(inst.BridgeGateway)
		mask := strings.TrimSpace(inst.BridgeNetmask)
		poolStart := strings.TrimSpace(inst.BridgePoolStart)
		poolEnd := strings.TrimSpace(inst.BridgePoolEnd)
		if gw == "" || mask == "" || poolStart == "" || poolEnd == "" {
			return fmt.Errorf("bridge_mode requires bridge_gateway, bridge_netmask, bridge_pool_start, bridge_pool_end")
		}
		fmt.Fprintf(b, "server-bridge %s %s %s %s\n", gw, mask, poolStart, poolEnd)
	} else if inst.ServerNetwork != "" {
		netw, mask, err := netutil.ServerNetworkToOpenVPN(inst.ServerNetwork)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "server %s %s\n", netw, mask)
	}
	if inst.ServerIPv6 != "" {
		fmt.Fprintf(b, "server-ipv6 %s\n", inst.ServerIPv6)
	}
	topo := inst.Topology
	if topo == "" {
		topo = "subnet"
	}
	fmt.Fprintf(b, "topology %s\n", topo)

	// ifconfig-pool is for non-bridge topology; bridge pool is part of server-bridge.
	if !inst.BridgeMode && inst.PoolStart != "" && inst.PoolEnd != "" {
		fmt.Fprintf(b, "ifconfig-pool %s %s\n", inst.PoolStart, inst.PoolEnd)
	}
	if inst.MaxClients > 0 {
		fmt.Fprintf(b, "max-clients %d\n", inst.MaxClients)
	}

	ccd := paths.CCDDir()
	fmt.Fprintf(b, "client-config-dir %s\n", ccd)
	fmt.Fprintf(b, "ccd-exclusive\n")

	for _, r := range inst.PushRoutes {
		r = strings.TrimSpace(r)
		if r == "" {
			continue
		}
		// Accept "10.0.0.0/24" or "10.0.0.0 255.255.255.0"
		if strings.Contains(r, "/") {
			n, m, err := netutil.ServerNetworkToOpenVPN(r)
			if err == nil {
				fmt.Fprintf(b, `push "route %s %s"`+"\n", n, m)
				continue
			}
		}
		fmt.Fprintf(b, `push "route %s"`+"\n", r)
	}
	for _, d := range inst.PushDNS {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		fmt.Fprintf(b, `push "dhcp-option DNS %s"`+"\n", d)
	}
	if inst.PushDomain != "" {
		fmt.Fprintf(b, `push "dhcp-option DOMAIN %s"`+"\n", inst.PushDomain)
	}
	if inst.RedirectGateway {
		fmt.Fprintf(b, `push "redirect-gateway def1 bypass-dhcp"`+"\n")
	}
	fmt.Fprintf(b, "duplicate-cn\n") // allow reconnect; suspend handled via CCD disable
	return nil
}

func renderClient(b *strings.Builder, inst db.Instance) error {
	fmt.Fprintf(b, "client\n")
	fmt.Fprintf(b, "tls-client\n")
	fmt.Fprintf(b, "nobind\n")
	fmt.Fprintf(b, "remote-cert-tls server\n")
	fmt.Fprintf(b, "resolv-retry infinite\n")
	// Local bind port (lport) is not taken from instance.Port — that field is
	// server listen / default remote port. Use extra_directives for rare lport needs.

	if len(inst.Remotes) == 0 {
		return fmt.Errorf("client instance requires at least one remote")
	}
	for _, r := range inst.Remotes {
		if r.Host == "" {
			continue
		}
		port := r.Port
		if port == 0 {
			port = 1194
		}
		if r.Proto != "" {
			fmt.Fprintf(b, "remote %s %d %s\n", r.Host, port, r.Proto)
		} else {
			fmt.Fprintf(b, "remote %s %d\n", r.Host, port)
		}
	}
	return nil
}

// RenderCCD builds a client-config-dir file body for one client.
func RenderCCD(c db.Client, serverNetwork string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# CN=%s\n", c.CommonName)
	if c.Suspended {
		// disable: refuse connection
		fmt.Fprintf(&b, "disable\n")
		return b.String()
	}
	if c.StaticIP != "" && serverNetwork != "" {
		// ifconfig-push requires client IP and local (server) IP for topology subnet
		// For topology subnet, second arg is netmask.
		if _, mask, err := netutil.ServerNetworkToOpenVPN(serverNetwork); err == nil {
			fmt.Fprintf(&b, "ifconfig-push %s %s\n", c.StaticIP, mask)
		} else {
			fmt.Fprintf(&b, "ifconfig-push %s 255.255.255.0\n", c.StaticIP)
		}
	}
	for _, r := range c.PushRoutes {
		r = strings.TrimSpace(r)
		if r == "" {
			continue
		}
		if strings.Contains(r, "/") {
			if n, m, err := netutil.ServerNetworkToOpenVPN(r); err == nil {
				fmt.Fprintf(&b, `push "route %s %s"`+"\n", n, m)
				continue
			}
		}
		fmt.Fprintf(&b, `push "route %s"`+"\n", r)
	}
	for _, d := range c.PushDNS {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		fmt.Fprintf(&b, `push "dhcp-option DNS %s"`+"\n", d)
	}
	if strings.TrimSpace(c.PushDomain) != "" {
		fmt.Fprintf(&b, `push "dhcp-option DOMAIN %s"`+"\n", strings.TrimSpace(c.PushDomain))
	}
	if c.RedirectGateway {
		fmt.Fprintf(&b, `push "redirect-gateway def1 bypass-dhcp"`+"\n")
	}
	// OpenVPN 2.5+: push-remove <opt> undoes a server-level push for this client.
	for _, opt := range c.DisablePush {
		opt = strings.TrimSpace(opt)
		if opt == "" {
			continue
		}
		fmt.Fprintf(&b, "push-remove %s\n", opt)
	}
	// iroute tells the server which subnets live behind this client (site-to-site).
	for _, r := range c.IRoutes {
		r = strings.TrimSpace(r)
		if r == "" {
			continue
		}
		if strings.Contains(r, "/") {
			if n, m, err := netutil.ServerNetworkToOpenVPN(r); err == nil {
				fmt.Fprintf(&b, "iroute %s %s\n", n, m)
				continue
			}
		}
		// Accept "net mask" already expanded
		fmt.Fprintf(&b, "iroute %s\n", r)
	}
	return b.String()
}

// SafeCNFilename sanitizes CN for CCD filename (OpenVPN uses CN as filename).
func SafeCNFilename(cn string) string {
	// OpenVPN CCD expects exact CN; only reject path separators.
	cn = strings.ReplaceAll(cn, "/", "_")
	cn = strings.ReplaceAll(cn, "\\", "_")
	cn = strings.ReplaceAll(cn, "..", "_")
	return cn
}
