package confgen_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/reloadlife/openvpnd/internal/confgen"
	"github.com/reloadlife/openvpnd/internal/db"
)

func TestRenderServer(t *testing.T) {
	inst := db.Instance{
		Name:          "ovpn0",
		Role:          "server",
		DevType:       "tun",
		Proto:         "udp",
		Port:          1194,
		ServerNetwork: "10.8.0.0/24",
		Topology:      "subnet",
		AuthMode:      "pki",
		PKICaPath:     "/pki/ca.crt",
		PKICertPath:   "/pki/server.crt",
		PKIKeyPath:    "/pki/server.key",
		PKIDHPath:     "/pki/dh.pem",
		PushDNS:       []string{"1.1.1.1"},
	}
	paths := confgen.Paths{ConfDir: "/etc/openvpnd/instances", RuntimeDir: "/run/openvpnd", Name: "ovpn0"}
	res, err := confgen.RenderInstance(inst, paths, nil)
	require.NoError(t, err)
	require.Contains(t, res.Content, "server 10.8.0.0 255.255.255.0")
	require.Contains(t, res.Content, "management ")
	require.Contains(t, res.Content, "client-config-dir")
	require.Contains(t, res.Content, `push "dhcp-option DNS 1.1.1.1"`)
	require.NotEmpty(t, res.Hash)
}

func TestRenderClient(t *testing.T) {
	inst := db.Instance{
		Name:     "home",
		Role:     "client",
		DevType:  "tun",
		Proto:    "udp",
		AuthMode: "pki",
		Remotes:  []db.Remote{{Host: "vpn.example.com", Port: 1194}},
		PKICaPath:   "/pki/ca.crt",
		PKICertPath: "/pki/client.crt",
		PKIKeyPath:  "/pki/client.key",
	}
	paths := confgen.Paths{ConfDir: "/tmp", RuntimeDir: "/tmp", Name: "home"}
	res, err := confgen.RenderInstance(inst, paths, nil)
	require.NoError(t, err)
	require.Contains(t, res.Content, "client")
	require.Contains(t, res.Content, "remote vpn.example.com 1194")
	require.True(t, strings.HasPrefix(res.Content, "# Generated by openvpnd"))
}

func TestRenderCCD(t *testing.T) {
	body := confgen.RenderCCD(db.Client{CommonName: "alice", StaticIP: "10.8.0.5"}, "10.8.0.0/24")
	require.Contains(t, body, "ifconfig-push 10.8.0.5")
	disabled := confgen.RenderCCD(db.Client{CommonName: "bob", Suspended: true}, "10.8.0.0/24")
	require.Contains(t, disabled, "disable")
}
