package confgen

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/reloadlife/openvpnd/internal/db"
	"github.com/reloadlife/openvpnd/internal/netutil"
)

// Paths holds runtime path helpers for an instance.
type Paths struct {
	ConfDir    string
	RuntimeDir string
	Name       string
}

func (p Paths) ConfFile() string {
	return filepath.Join(p.ConfDir, p.Name+".conf")
}

func (p Paths) PIDFile() string {
	return filepath.Join(p.RuntimeDir, p.Name+".pid")
}

func (p Paths) MgmtSock() string {
	return filepath.Join(p.RuntimeDir, p.Name+".mgmt.sock")
}

func (p Paths) StatusFile() string {
	return filepath.Join(p.RuntimeDir, p.Name+".status")
}

func (p Paths) CCDDir() string {
	return filepath.Join(p.ConfDir, "ccd", p.Name)
}

// RenderResult is generated conf content.
type RenderResult struct {
	Content string
	Hash    string
}

// Hash returns sha256 hex of content.
func Hash(content string) string {
	sum := sha256.Sum256([]byte(content))
	return hex.EncodeToString(sum[:])
}

// RenderInstance builds an OpenVPN conf for the instance.
// Management/status/pid are always injected for daemon control.
func RenderInstance(inst db.Instance, paths Paths, clients []db.Client) (RenderResult, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by openvpnd — do not edit by hand\n")
	fmt.Fprintf(&b, "# instance=%s role=%s\n", inst.Name, inst.Role)

	dev := inst.DevType
	if dev == "" {
		dev = "tun"
	}
	if inst.Device != "" {
		fmt.Fprintf(&b, "dev %s\n", inst.Device)
		fmt.Fprintf(&b, "dev-type %s\n", dev)
	} else {
		fmt.Fprintf(&b, "dev %s\n", dev)
	}

	proto := inst.Proto
	if proto == "" {
		proto = "udp"
	}
	fmt.Fprintf(&b, "proto %s\n", proto)

	if inst.LocalBind != "" {
		fmt.Fprintf(&b, "local %s\n", inst.LocalBind)
	}

	switch inst.Role {
	case "server":
		if err := renderServer(&b, inst, paths); err != nil {
			return RenderResult{}, err
		}
	case "client":
		if err := renderClient(&b, inst); err != nil {
			return RenderResult{}, err
		}
	default:
		return RenderResult{}, fmt.Errorf("unknown role %q", inst.Role)
	}

	// Crypto paths
	if inst.AuthMode == "static_key" || inst.StaticKeyPath != "" {
		if inst.StaticKeyPath != "" {
			fmt.Fprintf(&b, "secret %s\n", inst.StaticKeyPath)
		}
	} else {
		if inst.PKICaPath != "" {
			fmt.Fprintf(&b, "ca %s\n", inst.PKICaPath)
		}
		if inst.PKICertPath != "" {
			fmt.Fprintf(&b, "cert %s\n", inst.PKICertPath)
		}
		if inst.PKIKeyPath != "" {
			fmt.Fprintf(&b, "key %s\n", inst.PKIKeyPath)
		}
		if inst.PKIDHPath != "" && inst.Role == "server" {
			fmt.Fprintf(&b, "dh %s\n", inst.PKIDHPath)
		}
		if inst.PKITLSCryptPath != "" {
			fmt.Fprintf(&b, "tls-crypt %s\n", inst.PKITLSCryptPath)
		}
	}

	if inst.Cipher != "" {
		fmt.Fprintf(&b, "cipher %s\n", inst.Cipher)
	}
	if inst.DataCiphers != "" {
		fmt.Fprintf(&b, "data-ciphers %s\n", inst.DataCiphers)
	}
	if inst.AuthDigest != "" {
		fmt.Fprintf(&b, "auth %s\n", inst.AuthDigest)
	}

	// Always keepalive for NAT friendliness
	fmt.Fprintf(&b, "keepalive 10 60\n")
	fmt.Fprintf(&b, "persist-key\n")
	fmt.Fprintf(&b, "persist-tun\n")

	// Daemon control surface (always)
	fmt.Fprintf(&b, "writepid %s\n", paths.PIDFile())
	fmt.Fprintf(&b, "status %s 1\n", paths.StatusFile())
	fmt.Fprintf(&b, "management %s unix\n", paths.MgmtSock())
	fmt.Fprintf(&b, "management-client-user root\n")
	// Prefer not daemonizing so openvpnd can supervise; host backend may still detach via setsid.
	fmt.Fprintf(&b, "verb 3\n")

	if inst.ExtraDirectives != "" {
		fmt.Fprintf(&b, "\n# extra_directives\n%s\n", strings.TrimSpace(inst.ExtraDirectives))
	}

	// CCD content is separate files; still note client count for hash stability via included directives only.
	_ = clients

	content := b.String()
	return RenderResult{Content: content, Hash: Hash(content)}, nil
}

func renderServer(b *strings.Builder, inst db.Instance, paths Paths) error {
	port := inst.Port
	if port == 0 {
		port = 1194
	}
	fmt.Fprintf(b, "port %d\n", port)
	fmt.Fprintf(b, "mode server\n")
	fmt.Fprintf(b, "tls-server\n")

	if inst.ServerNetwork != "" {
		netw, mask, err := netutil.ServerNetworkToOpenVPN(inst.ServerNetwork)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "server %s %s\n", netw, mask)
	}
	topo := inst.Topology
	if topo == "" {
		topo = "subnet"
	}
	fmt.Fprintf(b, "topology %s\n", topo)

	if inst.PoolStart != "" && inst.PoolEnd != "" {
		fmt.Fprintf(b, "ifconfig-pool %s %s\n", inst.PoolStart, inst.PoolEnd)
	}

	ccd := paths.CCDDir()
	fmt.Fprintf(b, "client-config-dir %s\n", ccd)
	fmt.Fprintf(b, "ccd-exclusive\n")

	for _, r := range inst.PushRoutes {
		r = strings.TrimSpace(r)
		if r == "" {
			continue
		}
		// Accept "10.0.0.0/24" or "10.0.0.0 255.255.255.0"
		if strings.Contains(r, "/") {
			n, m, err := netutil.ServerNetworkToOpenVPN(r)
			if err == nil {
				fmt.Fprintf(b, `push "route %s %s"`+"\n", n, m)
				continue
			}
		}
		fmt.Fprintf(b, `push "route %s"`+"\n", r)
	}
	for _, d := range inst.PushDNS {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		fmt.Fprintf(b, `push "dhcp-option DNS %s"`+"\n", d)
	}
	if inst.PushDomain != "" {
		fmt.Fprintf(b, `push "dhcp-option DOMAIN %s"`+"\n", inst.PushDomain)
	}
	if inst.RedirectGateway {
		fmt.Fprintf(b, `push "redirect-gateway def1 bypass-dhcp"`+"\n")
	}
	fmt.Fprintf(b, "duplicate-cn\n") // allow reconnect; suspend handled via CCD disable
	return nil
}

func renderClient(b *strings.Builder, inst db.Instance) error {
	fmt.Fprintf(b, "client\n")
	fmt.Fprintf(b, "tls-client\n")
	fmt.Fprintf(b, "nobind\n")
	fmt.Fprintf(b, "remote-cert-tls server\n")
	fmt.Fprintf(b, "resolv-retry infinite\n")
	// Local bind port (lport) is not taken from instance.Port — that field is
	// server listen / default remote port. Use extra_directives for rare lport needs.

	if len(inst.Remotes) == 0 {
		return fmt.Errorf("client instance requires at least one remote")
	}
	for _, r := range inst.Remotes {
		if r.Host == "" {
			continue
		}
		port := r.Port
		if port == 0 {
			port = 1194
		}
		if r.Proto != "" {
			fmt.Fprintf(b, "remote %s %d %s\n", r.Host, port, r.Proto)
		} else {
			fmt.Fprintf(b, "remote %s %d\n", r.Host, port)
		}
	}
	return nil
}

// RenderCCD builds a client-config-dir file body for one client.
func RenderCCD(c db.Client, serverNetwork string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# CN=%s\n", c.CommonName)
	if c.Suspended {
		// disable: refuse connection
		fmt.Fprintf(&b, "disable\n")
		return b.String()
	}
	if c.StaticIP != "" && serverNetwork != "" {
		// ifconfig-push requires client IP and local (server) IP for topology subnet
		// For topology subnet, second arg is netmask.
		if _, mask, err := netutil.ServerNetworkToOpenVPN(serverNetwork); err == nil {
			fmt.Fprintf(&b, "ifconfig-push %s %s\n", c.StaticIP, mask)
		} else {
			fmt.Fprintf(&b, "ifconfig-push %s 255.255.255.0\n", c.StaticIP)
		}
	}
	for _, r := range c.PushRoutes {
		r = strings.TrimSpace(r)
		if r == "" {
			continue
		}
		if strings.Contains(r, "/") {
			if n, m, err := netutil.ServerNetworkToOpenVPN(r); err == nil {
				fmt.Fprintf(&b, `push "route %s %s"`+"\n", n, m)
				continue
			}
		}
		fmt.Fprintf(&b, `push "route %s"`+"\n", r)
	}
	return b.String()
}

// SafeCNFilename sanitizes CN for CCD filename (OpenVPN uses CN as filename).
func SafeCNFilename(cn string) string {
	// OpenVPN CCD expects exact CN; only reject path separators.
	cn = strings.ReplaceAll(cn, "/", "_")
	cn = strings.ReplaceAll(cn, "\\", "_")
	cn = strings.ReplaceAll(cn, "..", "_")
	return cn
}
